### ISSUE TITLE
请问支持下载共享链接里的文件吗？

### ISSUE THREAD

**Issue by Zhouxiaoqing** [axzxc1236/SharepointDownloader#3]
你好，请问这个工具支持类似于
    'https://1jjklacnz-my.sharepoint.com/personal/alog_1_jjkl_ac_nz/_layouts/15/onedrive.aspx?originalPath=aHR0cHM6Ly8xamprbGFjbnotbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvYWxvZ18xX2pqa2xfYWNfbnovRWt6ZDlYcG5KRzlJdVR3ZG85MnZFLS1ZWTlKaExZdz9ydGltZT0xbVlDTHJpTTJFZw&sortField=FileSizeDisplay&isAscending=true&id=%2Fpersonal%2Falog%5F1%5Fjjkl%5Fac%5Fnz%2FDocuments%2Ffx%2Fi%E6%98%A5%E7%A7%8B'
     这类共享链接的里的文件下载吗？
感谢！

**Comment by axzxc1236** [comment]
不行  這個應該是點下連結"之後導向到的"網址
(我不確定  我不想登入我的微軟帳號去嘗試)
這個軟體只支援"點下後帶你到這類網址"的網址
沒有打算支持需要登入微軟帳號的連結

**Comment by Zhouxiaoqing** [comment]
好的，谢谢啦！ : )
